/// <reference types = "Cypress"/>

import form from "../support/form";

const dataForm = require("../fixtures/data_form.json")
const formPage = new form()

describe('Automation testing for PT LNK technical test', ()=>{

    beforeEach("Product review form page is open", ()=>{
        cy.visit(dataForm.url_form)
        cy.wait(1000)
        cy.xpath(formPage.title_form).should('exist')
    })

    it('Fill product review form', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.fullName)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.rbtn_affordable).should('exist').click()
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_success_submit).should('exist')
    })

    it('Fill product review form with product or service other', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.fullName)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.field_other).should('exist').type(dataForm.productOrServiceOther)
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_success_submit).should('exist')
    })

    it('Submit other response', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.fullName)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.rbtn_affordable).should('exist').click()
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_success_submit).should('exist')
        cy.xpath(formPage.btn_otherResponse).should('exist').click()
        cy.xpath(formPage.title_form).should('exist')
    })

    it('Saving the response', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.fullName)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.rbtn_affordable).should('exist').click()
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_success_submit).should('exist')
        cy.xpath(formPage.btn_saveResponse).should('exist').click()
    })

    it('Submitting response with empty field', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_warning_fullName).should('exist')
        cy.xpath(formPage.title_warning_phoneNumber).should('exist')
        cy.xpath(formPage.title_warning_productOrServices).should('exist')
        cy.xpath(formPage.title_warning_rateOurServices).should('exist')
        cy.xpath(formPage.title_warning_reviewDate).should('exist')
    })

    it('Submitting response but "Full Name" field empty', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.rbtn_affordable).should('exist').click()
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_warning_fullName).should('exist')
    })

    it('Submitting response but "Phone Number" field empty', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.fullName)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.rbtn_affordable).should('exist').click()
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_warning_phoneNumber).should('exist')
    })

    it('Submitting response but "Product or services" question is empty', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_warning_productOrServices).should('exist')
    })

    it('Submitting response but "Rate our services" question is empty', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.fullName)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.rbtn_affordable).should('exist').click()
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.field_reviewDate).should('exist').click().click().type(dataForm.reviewDate)
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_warning_rateOurServices).should('exist')
    })

    it('Submitting response but "Review date" question is empty', ()=>{
        cy.xpath(formPage.title_fullName).should('exist')
        cy.xpath(formPage.field_fullName).should('exist').type(dataForm.fullName)
        cy.xpath(formPage.title_phoneNumber).should('exist')
        cy.xpath(formPage.field_phoneNumber).should('exist').type(dataForm.phoneNumber)
        cy.xpath(formPage.title_productOrService).should('exist')
        cy.xpath(formPage.rbtn_affordable).should('exist').click()
        cy.xpath(formPage.title_rate).should('exist')
        cy.xpath(formPage.btn_5star).should('exist').click()
        cy.xpath(formPage.title_reviewDate).should('exist')
        cy.xpath(formPage.btn_submit).should('exist').click()
        cy.xpath(formPage.title_warning_reviewDate).should('exist')
    })
})